---
- name: IRIS iris_qlist module demo
  ansible.builtin.debug:
    msg: "IRIS iris_qlist module demo"


# iris qlist

- name: Execute IRIS qlist
  iris_qlist:
    instance_name: 'IRIS'
  register: qlist_output

- name: Debug qlist_output
  ansible.builtin.debug:
    var: qlist_output

- name: Display qlist
  ansible.builtin.debug:
    msg: "qlist {{ qlist_output.fields }}"

- name: Create variables from dictionary
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ lookup('dict', qlist_output.fields) }}"

- name: Display qlist fields
  ansible.builtin.debug:
    msg: "iris is installed in: {{ iris_qlist_instance_install_directory }}"

- name: Display each field from qlist_output.fields
  ansible.builtin.debug:
    msg: "Key: {{ item.key }}, Value: {{ item.value }}"
  loop: "{{ lookup('dict', qlist_output.fields) }}"
  when: qlist_output.fields is defined


