---
- name: Install IRIS on database servers
  hosts: db_servers
  become: true
  become_user: root
  gather_facts: true

  vars:
    server_type: db_server
    iris_instance: "IRIS"

  roles:
    - install_iris
